!function(){function t(){function t(t,i,n,e){var a=t+n*Math.cos(e),o=i+n*Math.sin(e)
return{x:a,y:o}}function i(t,i){return t+Math.random()*(i-t)}function n(t){return t/180*Math.PI}function e(){var t=l.create(i(u/2,u),i(0,d/2),0,0)
t.setSpeed(i(p.min,p.max)),t.setHeading(n(v)),t.radius=D,t.opacity=0,t.trailLengthDelta=0,t.isSpawning=!0,t.isDying=!1,g.push(t)}function a(t){setTimeout(function(){t.isDying=!0},m)}function o(){if(!b){h.clearRect(0,0,u,d),h.fillStyle="#181818",h.fillRect(0,0,u,d),h.fill()
for(var t=0;t<f.length;t+=1){var i=f[t]
i.update(),s(i),i.x>u&&(i.x=0),i.x<0&&(i.x=u),i.y>d&&(i.y=0),i.y<0&&(i.y=d)}for(t=0;t<g.length;t+=1){var n=g[t]
n.isSpawning&&(n.opacity+=x,n.opacity>=1&&(n.isSpawning=!1,a(n))),n.isDying&&(n.opacity-=x,n.opacity<=0&&(n.isDying=!1,n.isDead=!0)),n.trailLengthDelta+=w,n.update(),n.opacity>0&&c(n)}for(t=g.length-1;t>=0;t--)g[t].isDead&&g.splice(t,1)}requestAnimationFrame(o)}function s(t){h.fillStyle="rgb(125, 249, 255)",h.beginPath(),h.arc(t.x,t.y,t.radius,0,2*Math.PI,!1),h.fill()}function c(i){var n=i.x,e=i.y,a=M*i.trailLengthDelta,o=t(n,e,-a,i.getHeading())
h.fillStyle="rgba(255, 255, 255, "+i.opacity+")"
var s=5
h.beginPath(),h.moveTo(n-1,e+1),h.lineTo(n,e+s),h.lineTo(n+1,e+1),h.lineTo(n+s,e),h.lineTo(n+1,e-1),h.lineTo(n,e+1),h.lineTo(n,e-s),h.lineTo(n-1,e-1),h.lineTo(n-s,e),h.lineTo(n-1,e+1),h.lineTo(n-s,e),h.closePath(),h.fill(),h.fillStyle="rgba(255, 221, 157, "+i.opacity+")",h.beginPath(),h.moveTo(n-1,e-1),h.lineTo(o.x,o.y),h.lineTo(n+1,e+1),h.closePath(),h.fill()}for(var l={x:0,y:0,vx:0,vy:0,radius:0,create:function(t,i,n,e){var a=Object.create(this)
return a.x=t,a.y=i,a.vx=Math.cos(e)*n,a.vy=Math.sin(e)*n,a},getSpeed:function(){return Math.sqrt(this.vx*this.vx+this.vy*this.vy)},setSpeed:function(t){var i=this.getHeading()
this.vx=Math.cos(i)*t,this.vy=Math.sin(i)*t},getHeading:function(){return Math.atan2(this.vy,this.vx)},setHeading:function(t){var i=this.getSpeed()
this.vx=Math.cos(t)*i,this.vy=Math.sin(t)*i},update:function(){this.x+=this.vx,this.y+=this.vy}},r=document.getElementById("canvas"),h=r.getContext("2d"),u=r.width=window.innerWidth,d=r.height=window.innerHeight,f=[],g=[],y=[{speed:.015,scale:.2,count:320},{speed:.03,scale:.5,count:50},{speed:.05,scale:.75,count:30}],v=145,p={min:10,max:20},x=.01,w=.01,T=2e3,m=500,M=300,S=2,D=3,b=!1,H=0;H<y.length;H+=1)for(var P=y[H],I=0;I<P.count;I+=1){var L=l.create(i(0,u),i(0,d),0,0)
L.radius=S*P.scale,L.setSpeed(P.speed),L.setHeading(n(v)),f.push(L)}o(),setInterval(function(){b||e()},T),window.onfocus=function(){b=!1},window.onblur=function(){b=!0}}window.onorientationchange=function(){window.location.reload()},window.onload=function(){setTimeout(t,200)}}()
